version: '3'

volumes:
  data:

services:
# https://github.com/ashleydavis/docker-compose-nodejs-with-typescript-example
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    restart: always
  app:
    container_name: simplequiz
    build: ./
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://docker:mongopw@mongodb:27017/simpleQuiz?authSource=admin
      - NODE_ENV=development
      - PORT=3000
      - SECRET_JWT=6Ff9jO/spXB8uMVcMwZClIlKN/BzkH4hHVssMc/rEN6MWt4Y3Xdfbsw4AAI/jmDIjGE5EFf34sth7A7cu8xYiL534ShJ17z0t2Z8mr9pfa+QjvG6MjoT0TZDblT5OdqUpXDlxvlb6WATF6n7bWPdIShMaQgoNU7JTE06XwWF+LETg2COdYfFwirUXj6mhyG4QOhlt5cpGQf2NOxdWPvSJ5ZELPLL2SmlGsni3EigrXxPYCuFA3xI9pIafHhGp9wVBfVVmdalpgQ4gKFewbU6KK4A0sEmZI/PWZB60soLuSHKBWqfDgENGIyofN2X/qaB5NqcyypCz54lFFyB1VOi/Q==
      - CLIENT_URL=localhost:3000
      - FROM_EMAIL=not-reply@simplequiz.com
    restart: always